---
title: "Assiment 2 - group 16"
author: "Bjark Dahl Mogensen, Mikkel Mertz og Benjamin Wedel Mathiasen"
date: "9. nov. 2015"
output: pdf_document
---



```{r}
library ("dplyr")
library ("rvest")
library ("readr")
library ("knitr")
library ("stringr")
library ("xml2")
library ("plyr")
```


```{r}
css.selector = " .location , .date , .transaction a , .name a , .heading-3 a , .views , .paid-amount span, .unique-reference "
link_ipaidabribe = paste("http://www.ipaidabribe.com/reports/all?page=", 1:200, sep = "")
link =  "http://www.ipaidabribe.com/reports/all#gsc.tab=0"

scrape_ipaidabribe = function (link_ipaidabribe) {
  my.link = read_html(link_ipaidabribe, encoding= "UTF-8")
  my.location = my.link %>%
    html_nodes(".location " ) %>%
    html_text()
  my.date = my.link %>%
    html_nodes(".date " ) %>%
    html_text()
  my.transactiondetail = my.link %>%
    html_nodes(".transaction a" ) %>%
    html_text()
  my.depname = my.link %>%
    html_nodes(".name a" ) %>%
    html_text()
  my.title = my.link %>%
    html_nodes(".heading-3 a" ) %>%
    html_text()
  my.views = my.link %>%
    html_nodes(".views" ) %>%
    html_text()
  my.payment = my.link %>%
    html_nodes(".paid-amount span" ) %>%
    html_text()
  my.refnumber = my.link %>%
    html_nodes(".unique-reference" ) %>%
    html_text()
  return (cbind(my.link, my.location, my.date, my.transactiondetail, my.depname, my.title, my.views, my.payment, my.refnumber))  
}

my.ipaidabribe.data = list() 
for (i in link_ipaidabribe[1:200]){
  print(paste("processing", i, sep = " "))
  my.ipaidabribe.data[[i]] = scrape_ipaidabribe(i)
    Sys.sleep(0.25)
  cat(" done!\n")
}

df=ldply(my.ipaidabribe.data, data.frame)


```





You can also embed plots, for example:

```{r, echo=FALSE}
plot(cars)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
